### ISSUE TITLE
Update from 1.1.5 to 2.0.7 did not work

### ISSUE THREAD

**Issue by Fiiti** [iobroker-community-adapters/ioBroker.mihome-vacuum#117]
**Hi,
tried to update from 1.1.5 to 2.0.7 using iobroker itself in the gui.
Get only errors:**
```
$ ./iobroker upgrade mihome-vacuum
Update mihome-vacuum from @1.1.5 to @2.0.7
NPM version: 6.14.4
npm install iobroker.mihome-vacuum@2.0.7 --loglevel error --prefix "/opt/iobroker" (System call)
internal/modules/cjs/loader.js:638    throw err;    ^Error: Cannot find module 'npmlog'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)    at Function.Module._load (internal/modules/cjs/loader.js:562:25)    at Module.require (internal/modules/cjs/loader.js:692:17)    at require (internal/modules/cjs/helpers.js:25:18)    at Object.<anonymous> (/opt/iobroker/node_modules/node-pre-gyp/lib/node-pre-gyp.js:16:11)    at Module._compile (internal/modules/cjs/loader.js:778:30)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)    at Module.load (internal/modules/cjs/loader.js:653:32)    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR!
 code ELIFECYCLEnpm ERR! errno 1npm ERR! canvas@2.6.1 install:  "node-pre-gyp install --fallback-to-build npm" ERR! Exit status 1
npm ERR! npm ERR! Failed at the canvas@2.6.1 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-04-17T09_18_05_553Z-debug.log
ERROR: host.nubroker Cannot install iobroker.mihome-vacuum@2.0.7: 1
ERROR: process exited with code 25`
```
**The logfile itself has adiitional infos about wrong OS ("Linux" instead of "Darwin"?!):
Just added only the last lines, because of the huge amount of lines**
``` _200 warn optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@^1.0.5 (node_modules/iobroker.info/node_modules/osx-temperature-sensor):
201 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
202 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
202 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
202 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
202 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
203 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
204 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
205 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
205 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
205 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
205 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
206 verbose stack Error: canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
206 verbose stack Exit status 1
206 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
206 verbose stack     at EventEmitter.emit (events.js:198:13)
206 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
206 verbose stack     at ChildProcess.emit (events.js:198:13)
206 verbose stack     at maybeClose (internal/child_process.js:982:16)
206 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
207 verbose pkgid canvas@2.6.1
208 verbose cwd /
209 verbose Linux 4.4.0-177-generic
210 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "iobroker.mihome-vacuum@2.0.7" "--loglevel" "error" "--prefix" "/opt/iobroker"
211 verbose node v10.20.1
212 verbose npm  v6.14.4
213 error code ELIFECYCLE
214 error errno 1
215 error canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
215 error Exit status 1
216 error Failed at the canvas@2.6.1 install script.
216 error This is probably not a problem with npm. There is likely additional logging output above.
217 verbose exit [ 1, true ]_
```
What would be the solution?

Fiiti

**Comment by Apollon77** [comment]
Is it  a linux system? If Linux please try

sudo apt-get install libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

And try again

**Comment by Fiiti** [comment]
I tried that already, but I did it again just to be sure.
Unfortunately, still the same problem.
![2020-04-21 16_25_53-galmi@nubroker_ ~](https://user-images.githubusercontent.com/25975978/79877859-0e61ce00-83ed-11ea-8d22-c5a70dddd9e5.png)

---------------

![2020-04-21 16_28_19-adapters - ioBroker und 2 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/25975978/79878051-42d58a00-83ed-11ea-9de0-7e5cdaa0a6f8.png)

```
$ ./iobroker upgrade mihome-vacuum
Update mihome-vacuum from @1.1.5 to @2.0.7
NPM version: 6.14.4
npm install iobroker.mihome-vacuum@2.0.7 --loglevel error --prefix "/opt/iobroker" (System call)
internal/modules/cjs/loader.js:638    throw err;    ^Error: Cannot find module 'npmlog'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)    at Function.Module._load (internal/modules/cjs/loader.js:562:25)    at Module.require (internal/modules/cjs/loader.js:692:17)    at require (internal/modules/cjs/helpers.js:25:18)    at Object.<anonymous> (/opt/iobroker/node_modules/node-pre-gyp/lib/node-pre-gyp.js:16:11)    at Module._compile (internal/modules/cjs/loader.js:778:30)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)    at Module.load (internal/modules/cjs/loader.js:653:32)    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
internal/modules/cjs/loader.js:638    throw err;    ^Error: Cannot find module 'npmlog'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)    at Function.Module._load (internal/modules/cjs/loader.js:562:25)    at Module.require (internal/modules/cjs/loader.js:692:17)    at require (internal/modules/cjs/helpers.js:25:18)    at Object.<anonymous> (/opt/iobroker/node_modules/node-pre-gyp/lib/node-pre-gyp.js:16:11)    at Module._compile (internal/modules/cjs/loader.js:778:30)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)    at Module.load (internal/modules/cjs/loader.js:653:32)    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR!
 code ELIFECYCLEnpm ERR! errno 1npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`npm ERR! Exit status 1
npm ERR! npm ERR! Failed at the canvas@2.6.1 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-04-21T14_28_57_015Z-debug.log
ERROR: host.nubroker Cannot install iobroker.mihome-vacuum@2.0.7: 1
ERROR: process exited with code 25
```

**Comment by dirkhe** [comment]
Did you Read the Readme https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum?

**Comment by Fiiti** [comment]
Of course, first thing! And not only did I read it, I executed it! (just kidding)

**Comment by dirkhe** [comment]
Please search the internet for installing canvas on your system.

**Comment by dirkhe** [comment]
Closed, because it is Common Problem with canvas and Not with Adapter
