### ISSUE TITLE
aktuelle notlösung für STYJ02YM (Mi Mop Pro) Viomi und co...

### ISSUE THREAD

**Issue by edicine** [iobroker-community-adapters/ioBroker.mihome-vacuum#180]
moin,
den sauger über home assistant einbinden, und dann über den hass adapter von iobroker verbinden.
https://github.com/Maczuga/home-assistant-vacuum-styj02ym

einen bestimmten raum über vis oder alexa reinigen lassen funktioniert auch. (alexa, sauge kinderzimmer ;)

gruss michael

**Comment by MeisterTR** [comment]
wie hast du das mit den räumen umgesetzt? in code vom link kann ich nix mit räumen erkennen, Die integration ist nur noch eine Zeitfrage. quick and dirty würde es schnell gehen. das bereitet aber nur noch mehr Probleme. deswegen habe ich mich für einen rebuild des adaptrers entschieden, in dem Zuge wird der Sauger dann auch voll unterstützt

**Comment by edicine** [comment]
> 
> 
> wie hast du das mit den räumen umgesetzt? in code vom link kann ich nix mit räumen erkennen, Die integration ist nur noch eine Zeitfrage. quick and dirty würde es schnell gehen. das bereitet aber nur noch mehr Probleme. deswegen habe ich mich für einen rebuild des adaptrers entschieden, in dem Zuge wird der Sauger dann auch voll unterstützt

das habe ich über ein script in home assistant laufen lassen, was über iobroker gestartet wird.

flur_vacuum:
  alias: flur mcfly
  sequence:
  - data:
      command: set_language
      entity_id: vacuum.McFly
      params: 2
    entity_id: vacuum.mcfly
    service: vacuum.send_command
  - data:
      command: set_mode_withroom
      entity_id: vacuum.McFly
      params:
      - 0
      - 1
      - 1
      - 14
    entity_id: vacuum.mcfly
    service: vacuum.send_command
  mode: single
-----------------------------------------------------------------------------------
params:
- 0 (0=Normal Vacuum, 1=Edge only)
- 1 (Don’t know what it does, have to test it, maybe number of passages)
- 1 (Quantity of rooms)
- 14 (Room ID)

bei der room id einfach ausprobieren, das geht bei 10 los. dann schauen wo er saugt.
mein kumpel meint das müssten die nummern sein die er am anfangt in der map einträgt, wenn er eine map erstellt.

ich habe die sachen auch nur im netz gefunden.
es ist nur komisch das mit dem iobroker vacuum adapter bei un nix geht..... findet unsere sauger garnicht.

gruss michael

**Comment by MeisterTR** [comment]
das liegt daran, dass alle sauger von xiaomi keine "echten" Xiaomis sind. es gibt 4 verschiedene Hersteller roborock, xiaomi, dreme und wie dieser hier viomi. Alle nutzen das Protokoll von Xiaomi, jedoch sind die daten die Gesendet werden alle unterschiedlich. von daher muss ich den adapter umbauen, da er nur au xiaomi/roborock ausgelegt ist.

**Comment by edicine** [comment]
ok, die frage ist, wird er irgentwann laufen? :)
bei homeassistant sind schon einige sachen weiter, selbst das neue Xiaomi Mijia Smart Multi-Mode Gateway (ZNDMWG03LM) funktioniert ohne probleme. nur mit Token ohne Key. 
https://github.com/AlexxIT/XiaomiGateway3

**Comment by MeisterTR** [comment]
Wie gesagt die neuprogrammierung des Adapters war zwingend erforderlich. Ich habe bei mir läuft der Sauger schon seit ein paar Wochen im Testbetrieb mit iobroker. Schätze dass ich in absehbarer Zeit die Version fertig habe.

**Comment by MeisterTR** [comment]
bitte mal von hier installieren, aber mitte  vorher den alten löschen.
[https://github.com/MeisterTR/ioBroker.mihome-vacuum](https://github.com/MeisterTR/ioBroker.mihome-vacuum)

[https://forum.iobroker.net/topic/37028/test-adapter-mihome-vacuum-3-x-x-styj02ym-viomi](https://forum.iobroker.net/topic/37028/test-adapter-mihome-vacuum-3-x-x-styj02ym-viomi)

gerne Testen und Rückmelden

**Comment by audi1503** [comment]
Der Adapter startet nicht, springt sofort auf rot  im log steht:

2020-09-22 20:16:59.073  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
--
2020-09-22 20:16:59.073  - error: mihome-vacuum.0 (13768) unhandled promise rejection: Unexpected end of JSON input
2020-09-22 20:16:59.074  - error: mihome-vacuum.0 (13768) SyntaxError: Unexpected end of JSON input

Alte instanz und Adapter gelöscht vorher und über git die 3.0.1 installiert

**Comment by MeisterTR** [comment]
schalte den adapter mal auf debug bitte damit ich sehe wo der feher geworfen wird

**Comment by MeisterTR** [comment]
hast du in der Config den sauger in dem Dropdown menü ausgewählt? fals nein, mach das mal

**Comment by audi1503** [comment]
soweit komme ich garnicht, der adapter spring sofort auf rot und dann steht da please activate instance beim Cloud login. reicht der der Log? 

2020-09-22 21:13:58.865  - debug: mihome-vacuum.0 (31802) Redis Objects: Use Redis connection: 127.0.0.1:9001
--
2020-09-22 21:13:58.890  - debug: mihome-vacuum.0 (31802) Objects client ready ... initialize now
2020-09-22 21:13:58.893  - debug: mihome-vacuum.0 (31802) Objects create System PubSub Client
2020-09-22 21:13:58.894  - debug: mihome-vacuum.0 (31802) Objects create User PubSub Client
2020-09-22 21:13:58.899  - debug: mihome-vacuum.0 (31802) Objects client initialize lua scripts
2020-09-22 21:13:58.912  - debug: mihome-vacuum.0 (31802) Objects connected to redis: 127.0.0.1:9001
2020-09-22 21:13:58.916  - debug: mihome-vacuum.0 (31802) objectDB connected
2020-09-22 21:13:58.917  - debug: mihome-vacuum.0 (31802) Redis States: Use Redis connection: 127.0.0.1:9000
2020-09-22 21:13:58.924  - debug: mihome-vacuum.0 (31802) States create User PubSub Client
2020-09-22 21:13:58.926  - debug: mihome-vacuum.0 (31802) States create System PubSub Client
2020-09-22 21:13:58.936  - debug: mihome-vacuum.0 (31802) States connected to redis: 127.0.0.1:9000
2020-09-22 21:13:58.937  - debug: mihome-vacuum.0 (31802) statesDB connected
2020-09-22 21:13:59.104  - info:  mihome-vacuum.0 (31802) starting. Version 3.0.1 in  /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.18.4,  js-controller: 3.1.6
2020-09-22 21:13:59.175  - info: mihome-vacuum.0 (31802) check user admin pw iobroker: true
2020-09-22 21:13:59.177  - info: mihome-vacuum.0 (31802) check group user admin group admin: false
2020-09-22 21:13:59.178  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
2020-09-22 21:13:59.178  - error: mihome-vacuum.0 (31802) unhandled promise rejection: Unexpected end of JSON input
2020-09-22 21:13:59.179  - error: mihome-vacuum.0 (31802) SyntaxError: Unexpected end of JSON input
at JSON.parse ()
at new Maphelper (/opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/maphelper.js:185:20)
at MihomeVacuum.onReady (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:193:15)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-09-22 21:13:59.226  - info: mihome-vacuum.0 (31802) terminating
2020-09-22 21:13:59.227  - info: mihome-vacuum.0 (31802) Terminated (NO_ERROR): Without reason
2020-09-22 21:13:59.752  - info: host.iobroker-Server instance system.adapter.mihome-vacuum.0 terminated with code 0 (NO_ERROR)
2020-09-22 21:13:59.752  - info: host.iobroker-Server Restart adapter system.adapter.mihome-vacuum.0 because enabled
2020-09-22 21:14:00.284  - debug: smartgarden.0 (23291) system.adapter.admin.0: logging true
2020-09-22 21:14:00.284  - debug: meross.0 (2431) system.adapter.admin.0: logging true
2020-09-22 21:14:29.778  - info: host.iobroker-Server instance system.adapter.mihome-vacuum.0 started with pid 31957
2020-09-22 21:14:30.368  - debug: mihome-vacuum.0 (31957) Redis Objects: Use Redis connection: 127.0.0.1:9001
2020-09-22 21:14:30.395  - debug: mihome-vacuum.0 (31957) Objects client ready ... initialize now
2020-09-22 21:14:30.397  - debug: mihome-vacuum.0 (31957) Objects create System PubSub Client
2020-09-22 21:14:30.398  - debug: mihome-vacuum.0 (31957) Objects create User PubSub Client
2020-09-22 21:14:30.404  - debug: mihome-vacuum.0 (31957) Objects client initialize lua scripts
2020-09-22 21:14:30.420  - debug: mihome-vacuum.0 (31957) Objects connected to redis: 127.0.0.1:9001
2020-09-22 21:14:30.424  - debug: mihome-vacuum.0 (31957) objectDB connected
2020-09-22 21:14:30.426  - debug: mihome-vacuum.0 (31957) Redis States: Use Redis connection: 127.0.0.1:9000
2020-09-22 21:14:30.433  - debug: mihome-vacuum.0 (31957) States create User PubSub Client
2020-09-22 21:14:30.435  - debug: mihome-vacuum.0 (31957) States create System PubSub Client
2020-09-22 21:14:30.444  - debug: mihome-vacuum.0 (31957) States connected to redis: 127.0.0.1:9000
2020-09-22 21:14:30.445  - debug: mihome-vacuum.0 (31957) statesDB connected
2020-09-22 21:14:30.759  - info:  mihome-vacuum.0 (31957) starting. Version 3.0.1 in  /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.18.4,  js-controller: 3.1.6
2020-09-22 21:14:30.830  - info: mihome-vacuum.0 (31957) check user admin pw iobroker: true
2020-09-22 21:14:30.832  - info: mihome-vacuum.0 (31957) check group user admin group admin: false
2020-09-22 21:14:30.833  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
2020-09-22 21:14:30.833  - error: mihome-vacuum.0 (31957) unhandled promise rejection: Unexpected end of JSON input
2020-09-22 21:14:30.834  - error: mihome-vacuum.0 (31957) SyntaxError: Unexpected end of JSON input
at JSON.parse ()
at new Maphelper (/opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/maphelper.js:185:20)
at MihomeVacuum.onReady (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:193:15)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-09-22 21:14:30.880  - info: mihome-vacuum.0 (31957) terminating
2020-09-22 21:14:30.881  - info: mihome-vacuum.0 (31957) Terminated (NO_ERROR): Without reason
2020-09-22 21:14:31.404  - info: host.iobroker-Server instance system.adapter.mihome-vacuum.0 terminated with code 0 (NO_ERROR)
2020-09-22 21:14:31.405  - info: host.iobroker-Server Restart adapter system.adapter.mihome-vacuum.0 because enabled

**Comment by audi1503** [comment]
So sieht es aus wenn ich den 2.2.4 installiert habe und den 3.0.1 drüber installiere:

2020-09-22 21:28:06.080 - debug: mihome-vacuum.0 (4290) MIIO: Config: ip:192.168.178.100 token: xxxxxxxxxxxxxxxxxxxxxxx
2020-09-22 21:28:06.085 - debug: mihome-vacuum.0 (4290) server started on 0.0.0.0:53421
2020-09-22 21:28:06.124 - debug: mihome-vacuum.0 (4290) MAIN: Connected to device, try to get model..
2020-09-22 21:28:06.126 - debug: mihome-vacuum.0 (4290) GETMODELFROMAPI: objModel: null
2020-09-22 21:28:08.129 - debug: mihome-vacuum.0 (4290) Get Device data..0
2020-09-22 21:28:08.611 - debug: mihome-vacuum.0 (4290) Xiaomi Cloud: Login successful
2020-09-22 21:28:10.132 - debug: mihome-vacuum.0 (4290) Get Device data..1
2020-09-22 21:28:10.955 - debug: mihome-vacuum.0 (4290) Tue Sep 22 2020 21:28:10 GMT+0200 (GMT+02:00)
2020-09-22 21:28:12.134 - debug: mihome-vacuum.0 (4290) Get Device data..2
2020-09-22 21:28:12.959 - debug: mihome-vacuum.0 (4290) Xiaomi Cloud: Login successful
2020-09-22 21:28:13.272 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-09-22 21:28:13.273 - error: mihome-vacuum.0 (4290) unhandled promise rejection: adapter is not defined
2020-09-22 21:28:13.274 - error: mihome-vacuum.0 (4290) ReferenceError: adapter is not defined
at /opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:397:29
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-09-22 21:28:13.280 - info: mihome-vacuum.0 (4290) terminating
2020-09-22 21:28:13.281 - info: mihome-vacuum.0 (4290) Terminated (NO_ERROR): Without reason
2020-09-22 21:28:13.802 - info: host.iobroker-Server instance system.adapter.mihome-vacuum.0 terminated with code 0 (NO_ERROR)
2020-09-22 21:28:13.803 - info: host.iobroker-Server Restart adapter system.adapter.mihome-vacuum.0 because enabled
2020-09-22 21:28:16.771 - debug: meross.0 (2431) system.adapter.admin.0: logging true
2020-09-22 21:28:16.771 - debug: smartgarden.0 (23291) system.adapter.admin.0: logging true

**Comment by MeisterTR** [comment]
sorry mein fehler, hatte noch eine alte version online, jetzt sollte es gehen

**Comment by audi1503** [comment]
Also Adapter steht jetzt auf Gelb  im Log steht:

2020-09-22 21:44:45.338 - debug: mihome-vacuum.0 (9884) MAIN: Connected to device, try to get model..
2020-09-22 21:44:45.342 - debug: mihome-vacuum.0 (9884) GETMODELFROMAPI: objModel: null
2020-09-22 21:44:47.347 - debug: mihome-vacuum.0 (9884) Get Device data..0
2020-09-22 21:44:49.350 - debug: mihome-vacuum.0 (9884) Get Device data..1
2020-09-22 21:44:51.353 - debug: mihome-vacuum.0 (9884) Get Device data..2
2020-09-22 21:44:53.356 - debug: mihome-vacuum.0 (9884) Get Device data..3
2020-09-22 21:44:55.360 - debug: mihome-vacuum.0 (9884) Get Device data..4
2020-09-22 21:44:55.361 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-09-22 21:44:55.362 - error: mihome-vacuum.0 (9884) unhandled promise rejection: Cannot read property 'val' of null
2020-09-22 21:44:55.363 - error: mihome-vacuum.0 (9884) TypeError: Cannot read property 'val' of null
at MihomeVacuum.getModel (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:102:37)

**Comment by MeisterTR** [comment]
das Sieht schon besser aus, versuch mal dich mit deinen nutzerdaten in der config anzumelden und wähle den sauger aus

**Comment by audi1503** [comment]
jetzt schreibt er:

2020-09-22 22:54:20.610  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
--
2020-09-22 22:54:20.610  - error: mihome-vacuum.0 (32501) unhandled promise rejection: deviceList[DeviceModel] is not a constructor
2020-09-22 22:54:20.611  - error: mihome-vacuum.0 (32501) TypeError: deviceList[DeviceModel] is not a constructor

und der Adapter springt auf rot

**Comment by audi1503** [comment]
Läuft jetzt 👍

**Comment by day-breaker** [comment]
Ich habe auch einen Mi Mop Pro (STYTJ01ZHM). Mit dieser Version läuft er jetzt auch soweit bei mir.
Leider geht jetzt nicht mehr der S50.
Folgende Fehlermeldung:
 Model roborock.vacuum.s5 not supported! Please open issue on git: https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues
@MeisterTR  Vielen Dank für deine tolle Arbeit. Find ich echt super.

**Comment by andiweli** [comment]
> Ich habe auch einen Mi Mop Pro (STYTJ01ZHM). Mit dieser Version läuft er jetzt auch soweit bei mir.

Hi - mit welcher Version hast du den 01er zum Laufen gebracht?
Dem "Hack" oder der Version von MeisterTR?
Danke!

**Comment by MeisterTR** [comment]
in 3.1.1 integriert
