### ISSUE TITLE
Fehlermeldung bei Raumreinigung

### ISSUE THREAD

**Issue by Baenker** [iobroker-community-adapters/ioBroker.mihome-vacuum#194]
Wenn ich einen einzelnen Raum reinigen lasse durch den Button roomClean verabschiedet sich danach die Instanz bei mir immer:

mihome-vacuum.0 | 2020-11-28 13:14:52.753 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
-- | -- | -- | --
mihome-vacuum.0 | 2020-11-28 13:14:52.753 | error | at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
mihome-vacuum.0 | 2020-11-28 13:14:52.753 | error | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
mihome-vacuum.0 | 2020-11-28 13:14:52.753 | error | at client.get (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:608:33)
mihome-vacuum.0 | 2020-11-28 13:14:52.753 | error | at /opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:187:68
mihome-vacuum.0 | 2020-11-28 13:14:52.753 | error | (12695) TypeError: Cannot read property 'val' of null
mihome-vacuum.0 | 2020-11-28 13:14:52.752 | error | (12695) uncaught exception: Cannot read property 'val' of null

Danach kommen normale Hinweise

mihome-vacuum.0 | 2020-11-28 13:16:06.290 | info | (12771) connecting, this can take up to 10 minutes ...
-- | -- | -- | --
mihome-vacuum.0 | 2020-11-28 13:15:46.326 | info | (12771) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-11-28 13:15:26.768 | info | (12771) set nächster Timer: Nicht verfügbar
mihome-vacuum.0 | 2020-11-28 13:15:26.363 | info | (12771) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-11-28 13:15:26.256 | info | (12771) New generation or new fw(3.5.8,4966) detected, create new states goto and zoneclean
mihome-vacuum.0 | 2020-11-28 13:15:26.225 | info | (12771) Cloud control disabled
mihome-vacuum.0 | 2020-11-28 13:15:26.224 | info | (12771) Expert mode disabled, states deleted
mihome-vacuum.0 | 2020-11-28 13:15:26.191 | info | (12771) starting. Version 2.1.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v10.18.1, js-controller: 3.1.6
host.iobroker_V41 | 2020-11-28 13:15:23.352 | info | instance system.adapter.mihome-vacuum.0 started with pid 12771
host.iobroker_V41 | 2020-11-28 13:14:53.330 | info | Restart adapter system.adapter.mihome-vacuum.0 because enabled
host.iobroker_V41 | 2020-11-28 13:14:53.329 | info | instance system.adapter.mihome-vacuum.0 terminated with code 0 (NO_ERROR)
mihome-vacuum.0 | 2020-11-28 13:14:52.800 | info | (12695) Terminated (NO_ERROR): Without reason
mihome-vacuum.0 | 2020-11-28 13:14:52.799 | info | (12695) terminating

wobei manche davon wohl auf debug könnten:

mihome-vacuum.0 | 2020-11-28 13:15:26.768 | info | (12771) set nächster Timer: Nicht verfügbar

Ich habe einen Roborock S6 max. Bei der Installtion kam eine Fehlermeldung wegen canvas. Wenn ich das richtig verstanden habe wird das nur für die Kartendarstellung benötigt. Da ich die eh nicht nutze habe ich es nicht nachinstalliert.

Ich will den Adapter eigentlich nur nutzen um bei Abwesenheit den sauger zu starten (alle Räume) oder je nach Situation automatisiert einzelne Räume zu reinigen.

Schmiert der Adapter nur bei mir ab bei einer Raumreinigung oder ist das ein generelles Problem?

Wobei bei mir der Datenpunkt room Clean auch nach der Installation leer war. Nach dem ich einmal ein true reingeschrieben habe, bleibt true stehen?

**Comment by Baenker** [comment]
Ok die Felder rommFanPower müssen gefüllt sein dann kommt auch kein Fehler
