### ISSUE TITLE
Exception and Adapter shutdown with JS-Controller 3.2.16

### ISSUE THREAD

**Issue by seb2010** [iobroker-community-adapters/ioBroker.mihome-vacuum#223]
Hello,
I do get repeated adapter-resets after thrown exceptions looking like this:

```

host.ioBroker-pi4 | 2021-03-10 13:36:46.668 | error | instance system.adapter.mihome-vacuum.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
mihome-vacuum.0 | 2021-03-10 13:36:46.051 | silly | (2396) States user redis pmessage io.mihome-vacuum.0.*/io.mihome-vacuum.0.info.connection:{"val":false,"ack":true,"ts":1615379806050,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.a
mihome-vacuum.0 | 2021-03-10 13:36:46.047 | warn | (2396) Terminated (UNCAUGHT_EXCEPTION): Without reason
mihome-vacuum.0 | 2021-03-10 13:36:46.045 | info | (2396) terminating
mihome-vacuum.0 | 2021-03-10 13:36:46.041 | silly | (2396) States system redis pmessage messagebox.system.adapter.mihome-vacuum.0/messagebox.system.adapter.mihome-vacuum.0:{"command":"addNotification","message":{"result":"ok"},"from":"system.host.ioBro
mihome-vacuum.0 | 2021-03-10 13:36:46.030 | error | (2396) The id "16" has an invalid type! Expected "string" or "object", received "number".
mihome-vacuum.0 | 2021-03-10 13:36:46.029 | error | (2396) Error: The id "16" has an invalid type! Expected "string" or "object", received "number". at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:505:19) at Adap
mihome-vacuum.0 | 2021-03-10 13:36:46.026 | error | (2396) unhandled promise rejection: The id "16" has an invalid type! Expected "string" or "object", received "number".
mihome-vacuum.0 | 2021-03-10 13:36:46.025 | error | (2396) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2021-03-10 13:36:46.023 | debug | (2396) sendMsg[1] >>> {"id":16,"method":"app_rc_start"}
mihome-vacuum.0 | 2021-03-10 13:36:46.022 | info | (2396) send message: Method: app_rc_start
```
Additionally the adapter seems to loose the connecting very quickly and cannot regain it. Maybe this is a side-effect or another issue, I do not know.

Regards
SEB

**Comment by radierer** [comment]
I have exactly the same problem. It first appears after an update of js-controller to 3.2.16 .. after a rollback to js-controller 3.1.6 everything worked fine again.

**Comment by seb2010** [comment]
The above error only appears when using custom commands.

I do get some additional error now though:
2021-03-12 22:30:06.794  -  mihome-vacuum.0 (31283) Cannot check object existence of "mihome-vacuum.0.control.connection": Connection is closed.
2021-03-12 22:30:06.794  -  mihome-vacuum.0 (31283) Cannot check object existence of "mihome-vacuum.0.control.spotclean": Connection is closed.
2021-03-12 22:30:06.840  -  mihome-vacuum.0 (31283) Could not check object existence of state mihome-vacuum.0.info.connection: Cannot check object existence of "mihome-vacuum.0.info.connection": Connection is closed.
2021-03-12 22:30:06.842  -  mihome-vacuum.0 (31283) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-03-12 22:30:06.843  -  mihome-vacuum.0 (31283) unhandled promise rejection: Could not check object existence of mihome-vacuum.0.control.spotclean: Cannot check object existence of "mihome-vacuum.0.control.spotclean": Connection is closed.
2021-03-12 22:30:06.852  -  mihome-vacuum.0 (31283) Error: Could not check object existence of mihome-vacuum.0.control.spotclean: Cannot check object existence of "mihome-vacuum.0.control.spotclean": Connection is closed.
    at Object.maybeCallbackWithError (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:2252:17)
    at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3314:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by radierer** [comment]
Jup .. the error only occurs if using custom commands. Curiously the adapter processed the command correct?! I also took a look in the changelog of the js-controller. With version 3.0.3 came the following optimization:

(Apollon77) Also catch unhandled promise rejections in adapters and handle like exceptions to allow error detection and automatic restart

What I didnt understand is, why didnt the error appears not till version 3.2.16??

In the meantime .. is there a way to manually send custom commands with the sendTo-block and parse the result to a string? My coding-skills are quiet not the beste ... :)

**Comment by seb2010** [comment]
a quick fix is to typecast the id for the function
`                adapter.setForeignState(id, state.val, true));`
in line 539 in the main.js into a String:
`                adapter.setForeignState(String(id), state.val, true));`
The warning might lead to follow up problems, but for now I can send the commands again.
Cheers
Sebastian

**Comment by a1development** [comment]
> a quick fix is to typecast the id for the function
> ` adapter.setForeignState(id, state.val, true));`
> in line 539 in the main.js into a String:
> ` adapter.setForeignState(String(id), state.val, true));`
> The warning might lead to follow up problems, but for now I can send the commands again.
> Cheers
> Sebastian

OK this did the trick. I replaced all 
`adapter.setForeignState(id,`
with 
`adapter.setForeignState(String(id),`
in the Adapter

**Comment by amathebest123** [comment]
Hi,
 I guess I got the same problem:

2021-03-24 08:07:10.225 - debug: mihome-vacuum.0 (22778) stateChange mihome-vacuum.0.control.X_send_command {"val":"app_zoned_clean;[[24500, 23500, 27000, 26000, 1]]","ack":false,"ts":1616569630222,"q":0,"c":"script.js.RoboRock.Raum_saugen_loop_3","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1616569630222}
--
2021-03-24 08:07:10.226 - info: mihome-vacuum.0 (22778) send message: Method: app_zoned_clean Params: [[24500, 23500, 27000, 26000, 1]]
2021-03-24 08:07:10.228 - debug: mihome-vacuum.0 (22778) sendMsg[1] >>> {"id":55,"method":"app_zoned_clean","params":[[24500,23500,27000,26000,1]]}
2021-03-24 08:07:10.231 - error: mihome-vacuum.0 (22778) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-03-24 08:07:10.232 - error: mihome-vacuum.0 (22778) unhandled promise rejection: The id "55" has an invalid type! Expected "string" or "object", received "number".
2021-03-24 08:07:10.237 - error: mihome-vacuum.0 (22778) Error: The id "55" has an invalid type! Expected "string" or "object", received "number".

for the replacement method you described perhaps a dumb question: where and how can I replace this line described?

**Comment by a1development** [comment]
@amathebest123 find the code in your ioBroker directory /node_modules/iobroker.mihome-vacuum/main.js

**Comment by olli0815** [comment]
same here, type-error, maybe it is worth to fix the apadpter as mentioned above - on githup...?

error: mihome-vacuum.0 (8089) The id "59" has an invalid type! Expected "string" or "object", received "number".

Anyway first of all thanks to providing the workaround / fix!

**Comment by seb2010** [comment]
basically, I do not know how to change it here. @MeisterTR, maybe you, as the latest contributor can look into this?

You can fix it yourself in the code on your machine. Instruction for the PI:
- navigate to the iobroker-directory: /opt/iobroker
- navigate to the modules sub-folder: /opt/iobroker/node_modules/iobroker.mihome-vacuum
- open the editor to edit the main.js: nano main.js
- search for "setForeignState" with: STRG+W
- you should find a line inside an IF-section with "command === X_send_command" as condition
- change
`adapter.setForeignState(id, state.val, true));`
into
`adapter.setForeignState(String(id), state.val, true));`
- save the changes: STRG+O
- quit the editor: STRG+X
- restart the adapter-instance

you will have changed the production code now. It will get replaced with future updates (i hope).

**Comment by olli0815** [comment]
sure I mean the adapter / code itselfe 
Anyway, search/replace ALL did the trick here as well.

Many thanks!
